[library]
work = [
  "src/*.vhd",
  "src/architectural_components/*.vhd",
  "src/control/*.vhd",
  "src/memory/*.vhd",
  "src/pipeline_registers/*.vhd",
  "src/stages/*.vhd",
  "src/testbenchs/*.vhd"
]
